-- 1. Users Table
CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(50) UNIQUE NOT NULL,
    FullName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETDATE() NOT NULL,
    UpdatedAt DATETIME2 NOT NULL
);

-- 2. Folders Table
CREATE TABLE Folders (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETDATE() NOT NULL,
    UpdatedAt DATETIME2 NOT NULL,
    CONSTRAINT FK_Folders_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

-- 3. Tags Table
CREATE TABLE Tags (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETDATE() NOT NULL,
    UpdatedAt DATETIME2 NOT NULL,
    CONSTRAINT FK_Tags_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CONSTRAINT UQ_User_TagName UNIQUE (UserId, Name)
);

-- 4. Bookmarks Table 
CREATE TABLE Bookmarks (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT NOT NULL,
    FolderId INT NULL,
    Title NVARCHAR(255) NOT NULL,
    Url NVARCHAR(MAX) NOT NULL,
    IconUrl NVARCHAR(MAX) NULL, 
    ImportHash VARCHAR(64) NULL, 
    IsFavorite BIT DEFAULT 0 NOT NULL, 
    LastVisitedAt DATETIME2 NULL, 
    CreatedAt DATETIME2 DEFAULT GETDATE() NOT NULL,
    UpdatedAt DATETIME2 NOT NULL,
    CONSTRAINT FK_Bookmarks_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CONSTRAINT FK_Bookmarks_Folders FOREIGN KEY (FolderId) REFERENCES Folders(Id) ON DELETE NO ACTION
);

-- 5. BookmarkTags Junction Table
CREATE TABLE BookmarkTags (
    BookmarkId INT NOT NULL,
    TagId INT NOT NULL,
    PRIMARY KEY (BookmarkId, TagId),
    CONSTRAINT FK_BT_Bookmark FOREIGN KEY (BookmarkId) REFERENCES Bookmarks(Id) ON DELETE CASCADE,
    CONSTRAINT FK_BT_Tag FOREIGN KEY (TagId) REFERENCES Tags(Id) ON DELETE NO ACTION
);