
-- 1. Users Table
CREATE TABLE Users (
    Id SERIAL PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL
);

-- 2. Folders Table
CREATE TABLE Folders (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    Name VARCHAR(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL
);

-- 3. Tags Table
CREATE TABLE Tags (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    Name VARCHAR(50) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL,
    UNIQUE (UserId, Name)
);

-- 4. Bookmarks Table
CREATE TABLE Bookmarks (
    Id SERIAL PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(Id) ON DELETE CASCADE,
    FolderId INT REFERENCES Folders(Id) ON DELETE CASCADE,
    Title VARCHAR(255) NOT NULL,
    Url TEXT NOT NULL,
    IconUrl TEXT NULL, 
    ImportHash VARCHAR(64) NULL, 
    IsFavorite BOOLEAN DEFAULT FALSE NOT NULL,
    LastVisitedAt TIMESTAMP NULL, 
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL
);

-- 5. BookmarkTags Junction Table
CREATE TABLE BookmarkTags (
    BookmarkId INT NOT NULL REFERENCES Bookmarks(Id) ON DELETE CASCADE,
    TagId INT NOT NULL REFERENCES Tags(Id) ON DELETE CASCADE,
    PRIMARY KEY (BookmarkId, TagId)
);